package com.iib.gov.repo.old;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.iib.gov.entity.vchvsEntityOld.VchvsEntity;

@Repository
//@Transactional
public interface VchvsRepo extends JpaRepository<VchvsEntity, String> {
	
//	@Query("from FruadEntity where input_inserted_date=:input_inserted_date and a_TXT_INSURER=:a_TXT_INSURER")
	
	
	  @Query(
	  value="SELECT distinct ID, TXT_POLICY_NUMBER,IDV,NCB_PER,NIL_DEP_FLAG,\r\n"
	  		+ "CASE WHEN CLASS_CODE = '11' THEN 'PRIVATE CAR'\r\n"
	  		+ "     WHEN CLASS_CODE = '12' THEN 'PRIVATE CAR (ONLY  THREE WHEELERS  WITH 750 TO 1000CC)'\r\n"
	  		+ "	 WHEN CLASS_CODE = '13' THEN 'PRIVATE CAR (ONLY  THREE WHEELERS  LESS THAN 750 )'\r\n"
	  		+ "	 WHEN CLASS_CODE = '14' THEN 'TWO WHEELERS'\r\n"
	  		+ "	 WHEN CLASS_CODE = '15' THEN 'TWO WHEELERS WITH SIDE CAR'\r\n"
	  		+ "	 WHEN CLASS_CODE = '16' THEN 'THREE WHEELER INVALID CARRIAGE WITH SIDE CAR -TREATED AS TWO WHEELER'\r\n"
	  		+ "	 WHEN CLASS_CODE = '17' THEN 'GOODS CARRYING VEHICLES OTHER THAN THREE WHEELERS - PUBLIC'\r\n"
	  		+ "	 WHEN CLASS_CODE = '18' THEN 'GOODS CARRYING VEHICLES OTHER THAN THREE WHEELERS - PRIVATE'\r\n"
	  		+ "	 WHEN CLASS_CODE = '19' THEN 'GOODS CARRYING MOTORISED  THREE WHEELERS AND  PEDAL CYCLES - PUBLIC'\r\n"
	  		+ "	 WHEN CLASS_CODE = '20' THEN 'GOODS CARRYING MOTORISED  THREE WHEELERS AND PEDAL CYCLES - PRIVATE'\r\n"
	  		+ "	 WHEN CLASS_CODE = '21' THEN 'PASSENGER CARRYING  FOUR WHEELED VEHICLES'\r\n"
	  		+ "	 WHEN CLASS_CODE = '22' THEN 'PASSENGER CARRYING  MOTORISED THREE WHEELED VEHICLES'\r\n"
	  		+ "	 WHEN CLASS_CODE = '23' THEN 'SPECIAL TYPE OF VEHICLES'\r\n"
	  		+ "	 WHEN CLASS_CODE = '24' THEN 'TWO WHEELERS - HIRE OR REWARD'\r\n"
	  		+ "	 WHEN CLASS_CODE = '25' THEN 'MOTOR TRADE ROAD TRANSIT RISK ONLY'\r\n"
	  		+ "	 WHEN CLASS_CODE = '26' THEN 'MOTOR TRADE ROAD RISK ONLY'\r\n"
	  		+ "	 WHEN CLASS_CODE = '27' THEN 'MOTOR TRADE INTERNAL RISK ONLY'\r\n"
	  		+ "	 WHEN CLASS_CODE = '28' THEN 'STANDALONE TRAILOR'\r\n"
	  		+ "	 WHEN CLASS_CODE = '29' THEN 'QUADRICYCLE (PVT. USE)'\r\n"
	  		+ "	 WHEN CLASS_CODE = '30' THEN 'QUADRICYCLE COMMERCIAL USE)' END CLASS_CODE,\r\n"
	  		+ "POLICY_START_DATE,\r\n"
	  		+ "POLICY_END_DATE,\r\n"
	  		+ "CASE WHEN POLICY_END_DATE >=GETDATE() THEN 'ACTIVE' ELSE 'INACTIVE' END POLICY_END_DATE,\r\n"
	  		+ "CASE WHEN TYPE_OF_POLICY = '1' THEN 'ANNUAL LIABILITY ONLY POLICY'\r\n"
	  		+ "     WHEN TYPE_OF_POLICY = '2' THEN 'ANNUAL PACKAGE POLICY'\r\n"
	  		+ "	 WHEN TYPE_OF_POLICY = '3' THEN 'FIRE ONLY POLICY'\r\n"
	  		+ "	 WHEN TYPE_OF_POLICY = '4' THEN 'THEFT ONLY POLICY'\r\n"
	  		+ "	 WHEN TYPE_OF_POLICY = '5' THEN 'FIRE AND THEFT ONLY POLICY'\r\n"
	  		+ "	 WHEN TYPE_OF_POLICY = '6' THEN 'LIABILITY ONLY WITH FIRE POLICY'\r\n"
	  		+ "	 WHEN TYPE_OF_POLICY = '7' THEN 'LIABILITY ONLY WITH THEFT POLICY'\r\n"
	  		+ "	 WHEN TYPE_OF_POLICY = '8' THEN 'LIABILITY ONLY WITH FIRE AND THEFT POLICY'\r\n"
	  		+ "	 WHEN TYPE_OF_POLICY = '9' THEN 'LONG TERM TWO WHEELER PACKAGE POLICY (OTHER THAN NEW BUSINESS)'\r\n"
	  		+ "	 WHEN TYPE_OF_POLICY = '10' THEN 'LONG TERM TWO WHEELER LIABILITY ONLY POLICY (OTHER THAN NEW BUSINESS)'\r\n"
	  		+ "	 WHEN TYPE_OF_POLICY = '11' THEN 'LONG TERM TWO WHEELER PACKAGE POLICY'\r\n"
	  		+ "	 WHEN TYPE_OF_POLICY = '12' THEN 'LONG TERM TWO WHEELER BUNDLED POLICY'\r\n"
	  		+ "	 WHEN TYPE_OF_POLICY = '13' THEN 'LONG TERM PRIVATE CAR PACKAGE POLICY'\r\n"
	  		+ "	 WHEN TYPE_OF_POLICY = '14' THEN 'LONG TERM PRIVATE CAR BUNDLED POLICY '\r\n"
	  		+ "	 WHEN TYPE_OF_POLICY = '15' THEN 'LONG TERM TWO WHEELER LIABILITY ONLY POLICY'\r\n"
	  		+ "	 WHEN TYPE_OF_POLICY = '16' THEN 'LONG TERM PRIVATE CAR LIABILITY ONLY POLICY'\r\n"
	  		+ "	 WHEN TYPE_OF_POLICY = '17' THEN 'STAND ALONE COMPULSORY PERSONAL ACCIDENT POLICY (OWNER-DRIVER)'\r\n"
	  		+ "	 WHEN TYPE_OF_POLICY = '18' THEN 'STAND ALONE OWN DAMAGE POLICY'\r\n"
	  		+ "	 ELSE 'NOT AVAILABLE' END TYPE_OF_POLICY,"
	  		+ " CASE WHEN TXT_INSURER = '556' THEN 'Oriental Insurance Co. Ltd.'\r\n"
	 		+ "	 when TXT_INSURER='545' then 'United India Insurance Co. Ltd.'\r\n"
	 		+ "	 when TXT_INSURER='132' then 'Future Generali General Insurance Co. Ltd.'\r\n"
	 		+ "	 when TXT_INSURER='123' then 'Cholamandalam MS General Insurance Co. Ltd.'\r\n"
	 		+ "	 when TXT_INSURER='115' then 'ICICI Lombard General Insurance Co. Ltd. '\r\n"
	 		+ "	 when TXT_INSURER='106' then 'IFFCO Tokio General Insurance Co. Ltd.'\r\n"
	 		+ "	  when TXT_INSURER='103' then 'Reliance General Insurance Co. Ltd.'\r\n"
	 		+ "	   when TXT_INSURER='141' then 'Raheja QBE General Insurance Co. Ltd.'\r\n"
	 		+ "	    when TXT_INSURER='137' then 'Shriram General Insurance Co. Ltd.'\r\n"
	 		+ "		 when TXT_INSURER='134' then 'Universal Sompo General Insurance Co. Ltd.'\r\n"
	 		+ "		  when TXT_INSURER='90' then 'New India Assurance Co. Ltd.'\r\n"
	 		+ "		   when TXT_INSURER='58' then 'National Insurance Co. Ltd.'\r\n"
	 		+ "		    when TXT_INSURER='113' then 'Bajaj Allianz General Insurance Co. Ltd.'\r\n"
	 		+ "		    when TXT_INSURER='139' then 'Bharti AXA General Insurance Co. Ltd.'\r\n"
	 		+ "			 when TXT_INSURER='108' then 'Tata AIG General Insurance Co. Ltd.'\r\n"
	 		+ "			  when TXT_INSURER='149' then 'Magma HDI General Insurance Co. Ltd.'\r\n"
	 		+ "			   when TXT_INSURER='144' then 'SBI General'\r\n"
	 		+ "			    when TXT_INSURER='150' then 'Liberty General Insurance Company Ltd.'\r\n"
	 		+ "				 when TXT_INSURER='152' then 'Kotak Mahindra General Insurance'\r\n"
	 		+ "				  when TXT_INSURER='102' then 'Royal Sundaram Alliance Insurance Co. Ltd.'\r\n"
	 		+ "				   when TXT_INSURER='146' then 'HDFC General Insurance Co Ltd.'\r\n"
	 		+ "				    when TXT_INSURER='155' then 'Navi General Insurance Ltd'\r\n"
	 		+ "					 when TXT_INSURER='158' then 'GoDigit General Insurance Ltd.'\r\n"
	 		+ "					  when TXT_INSURER='159' then 'Edelweiss General Insurance Co. Ltd.'\r\n"
	 		+ "					   when TXT_INSURER='157' then 'Acko General Insurance Limited' \r\n"
	  		+ "					   else 'Insurer Not available' end TXT_INSURER,"
	  		+ "case when TYPE_OF_TRANSACTION ='I' and POLICY_END_DATE>= GETDATE() then 'Active'\r\n"
	  		+ "     when TYPE_OF_TRANSACTION ='I' and POLICY_END_DATE< GETDATE() then 'Expired'\r\n"
	  		+ "	 when TYPE_OF_TRANSACTION ='C' then 'Cancelled' end TYPE_OF_TRANSACTION,\r\n"
	  		+ "case when INSERTED_DATE between '01-apr-2020' and '31-mar-2021' then 'FY2021'\r\n"
	  		+ "     when INSERTED_DATE between '01-apr-2021' and '31-mar-2022' then 'FY2122'\r\n"
	  		+ "	 when INSERTED_DATE between '01-apr-2022' and '31-mar-2023' then 'FY2223' "
	  		+ " when INSERTED_DATE between '01-apr-2023' and '31-mar-2024' then 'FY2324' end INSERTED_DATE\r\n"
	  		+ " FROM iiw_mot_policy_history_uat WITH (NOLOCK)\r\n"
	  		+ "WHERE TXT_CHASSIS_NUMBER = :chassisno order by TYPE_OF_TRANSACTION,INSERTED_DATE desc;"
	  
	  ,nativeQuery = true)
	 
	public List<VchvsEntity> findByChassisno(String chassisno);
	
	
	  @Query(
	  value="SELECT distinct ID, TXT_POLICY_NUMBER,IDV,NCB_PER,NIL_DEP_FLAG,\r\n"
	  		+ "	  		 CASE WHEN CLASS_CODE = '11' THEN 'PRIVATE CAR'\r\n"
	  		+ "	  		     WHEN CLASS_CODE = '12' THEN 'PRIVATE CAR (ONLY  THREE WHEELERS  WITH 750 TO 1000CC)'\r\n"
	  		+ "	  			 WHEN CLASS_CODE = '13' THEN 'PRIVATE CAR (ONLY  THREE WHEELERS  LESS THAN 750 )'\r\n"
	  		+ "	  			 WHEN CLASS_CODE = '14' THEN 'TWO WHEELERS'\r\n"
	  		+ "	  			 WHEN CLASS_CODE = '15' THEN 'TWO WHEELERS WITH SIDE CAR'\r\n"
	  		+ "	  			 WHEN CLASS_CODE = '16' THEN 'THREE WHEELER INVALID CARRIAGE WITH SIDE CAR -TREATED AS TWO WHEELER'\r\n"
	  		+ "	  			 WHEN CLASS_CODE = '17' THEN 'GOODS CARRYING VEHICLES OTHER THAN THREE WHEELERS - PUBLIC'\r\n"
	  		+ "	  			 WHEN CLASS_CODE = '18' THEN 'GOODS CARRYING VEHICLES OTHER THAN THREE WHEELERS - PRIVATE'\r\n"
	  		+ "	  			 WHEN CLASS_CODE = '19' THEN 'GOODS CARRYING MOTORISED  THREE WHEELERS AND  PEDAL CYCLES - PUBLIC'\r\n"
	  		+ "	  			 WHEN CLASS_CODE = '20' THEN 'GOODS CARRYING MOTORISED  THREE WHEELERS AND PEDAL CYCLES - PRIVATE'\r\n"
	  		+ "	  			 WHEN CLASS_CODE = '21' THEN 'PASSENGER CARRYING  FOUR WHEELED VEHICLES'\r\n"
	  		+ "	  			 WHEN CLASS_CODE = '22' THEN 'PASSENGER CARRYING  MOTORISED THREE WHEELED VEHICLES'\r\n"
	  		+ "	  			 WHEN CLASS_CODE = '23' THEN 'SPECIAL TYPE OF VEHICLES'\r\n"
	  		+ "	  			 WHEN CLASS_CODE = '24' THEN 'TWO WHEELERS - HIRE OR REWARD'\r\n"
	  		+ "	  			 WHEN CLASS_CODE = '25' THEN 'MOTOR TRADE ROAD TRANSIT RISK ONLY'\r\n"
	  		+ "	  			 WHEN CLASS_CODE = '26' THEN 'MOTOR TRADE ROAD RISK ONLY'\r\n"
	  		+ "	  			 WHEN CLASS_CODE = '27' THEN 'MOTOR TRADE INTERNAL RISK ONLY'\r\n"
	  		+ "	  			 WHEN CLASS_CODE = '28' THEN 'STANDALONE TRAILOR'\r\n"
	  		+ "	  			 WHEN CLASS_CODE = '29' THEN 'QUADRICYCLE (PVT. USE)'\r\n"
	  		+ "	  			 WHEN CLASS_CODE = '30' THEN 'QUADRICYCLE COMMERCIAL USE)' END CLASS_CODE,\r\n"
	  		+ "	  		POLICY_START_DATE,\r\n"
	  		+ "	  		POLICY_END_DATE,\r\n"
	  		+ "	  		CASE WHEN POLICY_END_DATE >=GETDATE() THEN 'ACTIVE' ELSE 'INACTIVE' END POLICY_END_DATE,\r\n"
	  		+ "	  		CASE WHEN TYPE_OF_POLICY = '1' THEN 'ANNUAL LIABILITY ONLY POLICY'\r\n"
	  		+ "	  		     WHEN TYPE_OF_POLICY = '2' THEN 'ANNUAL PACKAGE POLICY'\r\n"
	  		+ "	  			 WHEN TYPE_OF_POLICY = '3' THEN 'FIRE ONLY POLICY'\r\n"
	  		+ "	  			 WHEN TYPE_OF_POLICY = '4' THEN 'THEFT ONLY POLICY'\r\n"
	  		+ "	  			 WHEN TYPE_OF_POLICY = '5' THEN 'FIRE AND THEFT ONLY POLICY'\r\n"
	  		+ "	  			 WHEN TYPE_OF_POLICY = '6' THEN 'LIABILITY ONLY WITH FIRE POLICY'\r\n"
	  		+ "	  			 WHEN TYPE_OF_POLICY = '7' THEN 'LIABILITY ONLY WITH THEFT POLICY'\r\n"
	  		+ "	  			 WHEN TYPE_OF_POLICY = '8' THEN 'LIABILITY ONLY WITH FIRE AND THEFT POLICY'\r\n"
	  		+ "	  			 WHEN TYPE_OF_POLICY = '9' THEN 'LONG TERM TWO WHEELER PACKAGE POLICY (OTHER THAN NEW BUSINESS)'\r\n"
	  		+ "	  			 WHEN TYPE_OF_POLICY = '10' THEN 'LONG TERM TWO WHEELER LIABILITY ONLY POLICY (OTHER THAN NEW BUSINESS)'\r\n"
	  		+ "	  			 WHEN TYPE_OF_POLICY = '11' THEN 'LONG TERM TWO WHEELER PACKAGE POLICY'\r\n"
	  		+ "	  			 WHEN TYPE_OF_POLICY = '12' THEN 'LONG TERM TWO WHEELER BUNDLED POLICY'\r\n"
	  		+ "	  			 WHEN TYPE_OF_POLICY = '13' THEN 'LONG TERM PRIVATE CAR PACKAGE POLICY'\r\n"
	  		+ "	  			 WHEN TYPE_OF_POLICY = '14' THEN 'LONG TERM PRIVATE CAR BUNDLED POLICY '\r\n"
	  		+ "	  			 WHEN TYPE_OF_POLICY = '15' THEN 'LONG TERM TWO WHEELER LIABILITY ONLY POLICY'\r\n"
	  		+ "	  			 WHEN TYPE_OF_POLICY = '16' THEN 'LONG TERM PRIVATE CAR LIABILITY ONLY POLICY'\r\n"
	  		+ "	  			 WHEN TYPE_OF_POLICY = '17' THEN 'STAND ALONE COMPULSORY PERSONAL ACCIDENT POLICY (OWNER-DRIVER)'\r\n"
	  		+ "	  			 WHEN TYPE_OF_POLICY = '18' THEN 'STAND ALONE OWN DAMAGE POLICY'\r\n"
	  		+ "	  			 ELSE 'NOT AVAILABLE' END TYPE_OF_POLICY,\r\n"
	  		+ " CASE WHEN TXT_INSURER = '556' THEN 'Oriental Insurance Co. Ltd.'\r\n"
	 		+ "	 when TXT_INSURER='545' then 'United India Insurance Co. Ltd.'\r\n"
	 		+ "	 when TXT_INSURER='132' then 'Future Generali General Insurance Co. Ltd.'\r\n"
	 		+ "	 when TXT_INSURER='123' then 'Cholamandalam MS General Insurance Co. Ltd.'\r\n"
	 		+ "	 when TXT_INSURER='115' then 'ICICI Lombard General Insurance Co. Ltd. '\r\n"
	 		+ "	 when TXT_INSURER='106' then 'IFFCO Tokio General Insurance Co. Ltd.'\r\n"
	 		+ "	  when TXT_INSURER='103' then 'Reliance General Insurance Co. Ltd.'\r\n"
	 		+ "	   when TXT_INSURER='141' then 'Raheja QBE General Insurance Co. Ltd.'\r\n"
	 		+ "	    when TXT_INSURER='137' then 'Shriram General Insurance Co. Ltd.'\r\n"
	 		+ "		 when TXT_INSURER='134' then 'Universal Sompo General Insurance Co. Ltd.'\r\n"
	 		+ "		  when TXT_INSURER='90' then 'New India Assurance Co. Ltd.'\r\n"
	 		+ "		   when TXT_INSURER='58' then 'National Insurance Co. Ltd.'\r\n"
	 		+ "		    when TXT_INSURER='113' then 'Bajaj Allianz General Insurance Co. Ltd.'\r\n"
	 		+ "		    when TXT_INSURER='139' then 'Bharti AXA General Insurance Co. Ltd.'\r\n"
	 		+ "			 when TXT_INSURER='108' then 'Tata AIG General Insurance Co. Ltd.'\r\n"
	 		+ "			  when TXT_INSURER='149' then 'Magma HDI General Insurance Co. Ltd.'\r\n"
	 		+ "			   when TXT_INSURER='144' then 'SBI General'\r\n"
	 		+ "			    when TXT_INSURER='150' then 'Liberty General Insurance Company Ltd.'\r\n"
	 		+ "				 when TXT_INSURER='152' then 'Kotak Mahindra General Insurance'\r\n"
	 		+ "				  when TXT_INSURER='102' then 'Royal Sundaram Alliance Insurance Co. Ltd.'\r\n"
	 		+ "				   when TXT_INSURER='146' then 'HDFC General Insurance Co Ltd.'\r\n"
	 		+ "				    when TXT_INSURER='155' then 'Navi General Insurance Ltd'\r\n"
	 		+ "					 when TXT_INSURER='158' then 'GoDigit General Insurance Ltd.'\r\n"
	 		+ "					  when TXT_INSURER='159' then 'Edelweiss General Insurance Co. Ltd.'\r\n"
	 		+ "					   when TXT_INSURER='157' then 'Acko General Insurance Limited' \r\n"
	  		+ "	  							   else 'Insurer Not available' end TXT_INSURER,\r\n"
	  		+ "	  		case when TYPE_OF_TRANSACTION ='I' and cast(POLICY_END_DATE AS date)>= cast(GETDATE() AS date) then 'Active'\r\n"
	  		+ "	  		     when TYPE_OF_TRANSACTION ='I' and cast(POLICY_END_DATE AS date)< cast(GETDATE() AS date) then 'Expired'\r\n"
	  		+ "	  			 when TYPE_OF_TRANSACTION ='C' then 'Cancelled' end TYPE_OF_TRANSACTION,\r\n"
	  		+ "	  		case when INSERTED_DATE between '01-apr-2020' and '31-mar-2021' then 'FY2021'\r\n"
	  		+ "	  		     when INSERTED_DATE between '01-apr-2021' and '31-mar-2022' then 'FY2122'\r\n"
	  		+ "	  			 when INSERTED_DATE between '01-apr-2022' and '31-mar-2023' then 'FY2223'"
	  		+ " when INSERTED_DATE between '01-apr-2023' and '31-mar-2024' then 'FY2324' end INSERTED_DATE\r\n"
	  		+ "	  		 FROM iiw_mot_policy_history_uat WITH (NOLOCK)\r\n"
	  		+ "	  		WHERE TXT_REG_NUMBER_VEHICLE =:regno \r\n"
	  		+ "			order by TYPE_OF_TRANSACTION,INSERTED_DATE desc;"
	  
	  ,nativeQuery = true)
	 
	public List<VchvsEntity> findByRegno(String regno);

	
	 @Query(value="SELECT distinct ID,TXT_POLICY_NUMBER,IDV,NCB_PER,NIL_DEP_FLAG,\r\n"
	 		+ "CASE WHEN CLASS_CODE = '11' THEN 'PRIVATE CAR'\r\n"
	 		+ "     WHEN CLASS_CODE = '12' THEN 'PRIVATE CAR (ONLY  THREE WHEELERS  WITH 750 TO 1000CC)'\r\n"
	 		+ "	 WHEN CLASS_CODE = '13' THEN 'PRIVATE CAR (ONLY  THREE WHEELERS  LESS THAN 750 )'\r\n"
	 		+ "	 WHEN CLASS_CODE = '14' THEN 'TWO WHEELERS'\r\n"
	 		+ "	 WHEN CLASS_CODE = '15' THEN 'TWO WHEELERS WITH SIDE CAR'\r\n"
	 		+ "	 WHEN CLASS_CODE = '16' THEN 'THREE WHEELER INVALID CARRIAGE WITH SIDE CAR -TREATED AS TWO WHEELER'\r\n"
	 		+ "	 WHEN CLASS_CODE = '17' THEN 'GOODS CARRYING VEHICLES OTHER THAN THREE WHEELERS - PUBLIC'\r\n"
	 		+ "	 WHEN CLASS_CODE = '18' THEN 'GOODS CARRYING VEHICLES OTHER THAN THREE WHEELERS - PRIVATE'\r\n"
	 		+ "	 WHEN CLASS_CODE = '19' THEN 'GOODS CARRYING MOTORISED  THREE WHEELERS AND  PEDAL CYCLES - PUBLIC'\r\n"
	 		+ "	 WHEN CLASS_CODE = '20' THEN 'GOODS CARRYING MOTORISED  THREE WHEELERS AND PEDAL CYCLES - PRIVATE'\r\n"
	 		+ "	 WHEN CLASS_CODE = '21' THEN 'PASSENGER CARRYING  FOUR WHEELED VEHICLES'\r\n"
	 		+ "	 WHEN CLASS_CODE = '22' THEN 'PASSENGER CARRYING  MOTORISED THREE WHEELED VEHICLES'\r\n"
	 		+ "	 WHEN CLASS_CODE = '23' THEN 'SPECIAL TYPE OF VEHICLES'\r\n"
	 		+ "	 WHEN CLASS_CODE = '24' THEN 'TWO WHEELERS - HIRE OR REWARD'\r\n"
	 		+ "	 WHEN CLASS_CODE = '25' THEN 'MOTOR TRADE ROAD TRANSIT RISK ONLY'\r\n"
	 		+ "	 WHEN CLASS_CODE = '26' THEN 'MOTOR TRADE ROAD RISK ONLY'\r\n"
	 		+ "	 WHEN CLASS_CODE = '27' THEN 'MOTOR TRADE INTERNAL RISK ONLY'\r\n"
	 		+ "	 WHEN CLASS_CODE = '28' THEN 'STANDALONE TRAILOR'\r\n"
	 		+ "	 WHEN CLASS_CODE = '29' THEN 'QUADRICYCLE (PVT. USE)'\r\n"
	 		+ "	 WHEN CLASS_CODE = '30' THEN 'QUADRICYCLE COMMERCIAL USE)' END CLASS_CODE,\r\n"
	 		+ "POLICY_START_DATE,\r\n"
	 		+ "POLICY_END_DATE,\r\n"
	 		+ "CASE WHEN POLICY_END_DATE >=GETDATE() THEN 'ACTIVE' ELSE 'INACTIVE' END POLICY_END_DATE,\r\n"
	 		+ "CASE WHEN TYPE_OF_POLICY = '1' THEN 'ANNUAL LIABILITY ONLY POLICY'\r\n"
	 		+ "     WHEN TYPE_OF_POLICY = '2' THEN 'ANNUAL PACKAGE POLICY'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '3' THEN 'FIRE ONLY POLICY'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '4' THEN 'THEFT ONLY POLICY'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '5' THEN 'FIRE AND THEFT ONLY POLICY'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '6' THEN 'LIABILITY ONLY WITH FIRE POLICY'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '7' THEN 'LIABILITY ONLY WITH THEFT POLICY'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '8' THEN 'LIABILITY ONLY WITH FIRE AND THEFT POLICY'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '9' THEN 'LONG TERM TWO WHEELER PACKAGE POLICY (OTHER THAN NEW BUSINESS)'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '10' THEN 'LONG TERM TWO WHEELER LIABILITY ONLY POLICY (OTHER THAN NEW BUSINESS)'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '11' THEN 'LONG TERM TWO WHEELER PACKAGE POLICY'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '12' THEN 'LONG TERM TWO WHEELER BUNDLED POLICY'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '13' THEN 'LONG TERM PRIVATE CAR PACKAGE POLICY'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '14' THEN 'LONG TERM PRIVATE CAR BUNDLED POLICY '\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '15' THEN 'LONG TERM TWO WHEELER LIABILITY ONLY POLICY'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '16' THEN 'LONG TERM PRIVATE CAR LIABILITY ONLY POLICY'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '17' THEN 'STAND ALONE COMPULSORY PERSONAL ACCIDENT POLICY (OWNER-DRIVER)'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '18' THEN 'STAND ALONE OWN DAMAGE POLICY'\r\n"
	 		+ "	 ELSE 'NOT AVAILABLE' END TYPE_OF_POLICY,"
	 		+ " CASE WHEN TXT_INSURER = '556' THEN 'Oriental Insurance Co. Ltd.'\r\n"
	 		+ "	 when TXT_INSURER='545' then 'United India Insurance Co. Ltd.'\r\n"
	 		+ "	 when TXT_INSURER='132' then 'Future Generali General Insurance Co. Ltd.'\r\n"
	 		+ "	 when TXT_INSURER='123' then 'Cholamandalam MS General Insurance Co. Ltd.'\r\n"
	 		+ "	 when TXT_INSURER='115' then 'ICICI Lombard General Insurance Co. Ltd. '\r\n"
	 		+ "	 when TXT_INSURER='106' then 'IFFCO Tokio General Insurance Co. Ltd.'\r\n"
	 		+ "	  when TXT_INSURER='103' then 'Reliance General Insurance Co. Ltd.'\r\n"
	 		+ "	   when TXT_INSURER='141' then 'Raheja QBE General Insurance Co. Ltd.'\r\n"
	 		+ "	    when TXT_INSURER='137' then 'Shriram General Insurance Co. Ltd.'\r\n"
	 		+ "		 when TXT_INSURER='134' then 'Universal Sompo General Insurance Co. Ltd.'\r\n"
	 		+ "		  when TXT_INSURER='90' then 'New India Assurance Co. Ltd.'\r\n"
	 		+ "		   when TXT_INSURER='58' then 'National Insurance Co. Ltd.'\r\n"
	 		+ "		    when TXT_INSURER='113' then 'Bajaj Allianz General Insurance Co. Ltd.'\r\n"
	 		+ "		    when TXT_INSURER='139' then 'Bharti AXA General Insurance Co. Ltd.'\r\n"
	 		+ "			 when TXT_INSURER='108' then 'Tata AIG General Insurance Co. Ltd.'\r\n"
	 		+ "			  when TXT_INSURER='149' then 'Magma HDI General Insurance Co. Ltd.'\r\n"
	 		+ "			   when TXT_INSURER='144' then 'SBI General'\r\n"
	 		+ "			    when TXT_INSURER='150' then 'Liberty General Insurance Company Ltd.'\r\n"
	 		+ "				 when TXT_INSURER='152' then 'Kotak Mahindra General Insurance'\r\n"
	 		+ "				  when TXT_INSURER='102' then 'Royal Sundaram Alliance Insurance Co. Ltd.'\r\n"
	 		+ "				   when TXT_INSURER='146' then 'HDFC General Insurance Co Ltd.'\r\n"
	 		+ "				    when TXT_INSURER='155' then 'Navi General Insurance Ltd'\r\n"
	 		+ "					 when TXT_INSURER='158' then 'GoDigit General Insurance Ltd.'\r\n"
	 		+ "					  when TXT_INSURER='159' then 'Edelweiss General Insurance Co. Ltd.'\r\n"
	 		+ "					   when TXT_INSURER='157' then 'Acko General Insurance Limited' \r\n"
	 		+ "					   else 'Insurer Not available' end TXT_INSURER,"
	 		+ "case when TYPE_OF_TRANSACTION ='I' and POLICY_END_DATE>= GETDATE() then 'Active'\r\n"
	 		+ "     when TYPE_OF_TRANSACTION ='I' and POLICY_END_DATE< GETDATE() then 'Expired'\r\n"
	 		+ "	 when TYPE_OF_TRANSACTION ='C' then 'Cancelled' end TYPE_OF_TRANSACTION,\r\n"
	 		+ "case when INSERTED_DATE between '01-apr-2020' and '31-mar-2021' then 'FY2021'\r\n"
	 		+ "     when INSERTED_DATE between '01-apr-2021' and '31-mar-2022' then 'FY2122'\r\n"
	 		+ "	 when INSERTED_DATE between '01-apr-2022' and '31-mar-2023' then 'FY2223'"
	 		+ " when INSERTED_DATE between '01-apr-2023' and '31-mar-2024' then 'FY2324' end INSERTED_DATE\r\n"
	 		+ " FROM iiw_mot_policy_history_uat WITH (NOLOCK)\r\n"
	 		+ "WHERE TXT_REG_NUMBER_VEHICLE = :regno OR TXT_CHASSIS_NUMBER =:chassisno order by TYPE_OF_TRANSACTION,INSERTED_DATE desc;" ,nativeQuery = true)
	// @Query(value=" from VchvsEntity where regno=:regno and chassisno=:chassisno ORDER BY CustomerName DESC")
	public List<VchvsEntity> RegnoAndChassisno(String regno,String chassisno);
	 
	 @Query(value="SELECT distinct ID, TXT_POLICY_NUMBER,IDV,NCB_PER,NIL_DEP_FLAG,\r\n"
	 		+ "CASE WHEN CLASS_CODE = '11' THEN 'PRIVATE CAR'\r\n"
	 		+ "     WHEN CLASS_CODE = '12' THEN 'PRIVATE CAR (ONLY  THREE WHEELERS  WITH 750 TO 1000CC)'\r\n"
	 		+ "	 WHEN CLASS_CODE = '13' THEN 'PRIVATE CAR (ONLY  THREE WHEELERS  LESS THAN 750 )'\r\n"
	 		+ "	 WHEN CLASS_CODE = '14' THEN 'TWO WHEELERS'\r\n"
	 		+ "	 WHEN CLASS_CODE = '15' THEN 'TWO WHEELERS WITH SIDE CAR'\r\n"
	 		+ "	 WHEN CLASS_CODE = '16' THEN 'THREE WHEELER INVALID CARRIAGE WITH SIDE CAR -TREATED AS TWO WHEELER'\r\n"
	 		+ "	 WHEN CLASS_CODE = '17' THEN 'GOODS CARRYING VEHICLES OTHER THAN THREE WHEELERS - PUBLIC'\r\n"
	 		+ "	 WHEN CLASS_CODE = '18' THEN 'GOODS CARRYING VEHICLES OTHER THAN THREE WHEELERS - PRIVATE'\r\n"
	 		+ "	 WHEN CLASS_CODE = '19' THEN 'GOODS CARRYING MOTORISED  THREE WHEELERS AND  PEDAL CYCLES - PUBLIC'\r\n"
	 		+ "	 WHEN CLASS_CODE = '20' THEN 'GOODS CARRYING MOTORISED  THREE WHEELERS AND PEDAL CYCLES - PRIVATE'\r\n"
	 		+ "	 WHEN CLASS_CODE = '21' THEN 'PASSENGER CARRYING  FOUR WHEELED VEHICLES'\r\n"
	 		+ "	 WHEN CLASS_CODE = '22' THEN 'PASSENGER CARRYING  MOTORISED THREE WHEELED VEHICLES'\r\n"
	 		+ "	 WHEN CLASS_CODE = '23' THEN 'SPECIAL TYPE OF VEHICLES'\r\n"
	 		+ "	 WHEN CLASS_CODE = '24' THEN 'TWO WHEELERS - HIRE OR REWARD'\r\n"
	 		+ "	 WHEN CLASS_CODE = '25' THEN 'MOTOR TRADE ROAD TRANSIT RISK ONLY'\r\n"
	 		+ "	 WHEN CLASS_CODE = '26' THEN 'MOTOR TRADE ROAD RISK ONLY'\r\n"
	 		+ "	 WHEN CLASS_CODE = '27' THEN 'MOTOR TRADE INTERNAL RISK ONLY'\r\n"
	 		+ "	 WHEN CLASS_CODE = '28' THEN 'STANDALONE TRAILOR'\r\n"
	 		+ "	 WHEN CLASS_CODE = '29' THEN 'QUADRICYCLE (PVT. USE)'\r\n"
	 		+ "	 WHEN CLASS_CODE = '30' THEN 'QUADRICYCLE COMMERCIAL USE)' END CLASS_CODE,\r\n"
	 		+ "POLICY_START_DATE,\r\n"
	 		+ "POLICY_END_DATE,\r\n"
	 		+ "CASE WHEN POLICY_END_DATE >=GETDATE() THEN 'ACTIVE' ELSE 'INACTIVE' END,\r\n"
	 		+ "CASE WHEN TYPE_OF_POLICY = '1' THEN 'ANNUAL LIABILITY ONLY POLICY'\r\n"
	 		+ "     WHEN TYPE_OF_POLICY = '2' THEN 'ANNUAL PACKAGE POLICY'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '3' THEN 'FIRE ONLY POLICY'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '4' THEN 'THEFT ONLY POLICY'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '5' THEN 'FIRE AND THEFT ONLY POLICY'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '6' THEN 'LIABILITY ONLY WITH FIRE POLICY'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '7' THEN 'LIABILITY ONLY WITH THEFT POLICY'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '8' THEN 'LIABILITY ONLY WITH FIRE AND THEFT POLICY'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '9' THEN 'LONG TERM TWO WHEELER PACKAGE POLICY (OTHER THAN NEW BUSINESS)'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '10' THEN 'LONG TERM TWO WHEELER LIABILITY ONLY POLICY (OTHER THAN NEW BUSINESS)'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '11' THEN 'LONG TERM TWO WHEELER PACKAGE POLICY'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '12' THEN 'LONG TERM TWO WHEELER BUNDLED POLICY'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '13' THEN 'LONG TERM PRIVATE CAR PACKAGE POLICY'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '14' THEN 'LONG TERM PRIVATE CAR BUNDLED POLICY '\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '15' THEN 'LONG TERM TWO WHEELER LIABILITY ONLY POLICY'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '16' THEN 'LONG TERM PRIVATE CAR LIABILITY ONLY POLICY'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '17' THEN 'STAND ALONE COMPULSORY PERSONAL ACCIDENT POLICY (OWNER-DRIVER)'\r\n"
	 		+ "	 WHEN TYPE_OF_POLICY = '18' THEN 'STAND ALONE OWN DAMAGE POLICY'\r\n"
	 		+ "	 ELSE 'NOT AVAILABLE' END TYPE_OF_POLICY, "
	 		+ " CASE WHEN TXT_INSURER = '556' THEN 'Oriental Insurance Co. Ltd.'\r\n"
	 		+ "	 when TXT_INSURER='545' then 'United India Insurance Co. Ltd.'\r\n"
	 		+ "	 when TXT_INSURER='132' then 'Future Generali General Insurance Co. Ltd.'\r\n"
	 		+ "	 when TXT_INSURER='123' then 'Cholamandalam MS General Insurance Co. Ltd.'\r\n"
	 		+ "	 when TXT_INSURER='115' then 'ICICI Lombard General Insurance Co. Ltd. '\r\n"
	 		+ "	 when TXT_INSURER='106' then 'IFFCO Tokio General Insurance Co. Ltd.'\r\n"
	 		+ "	  when TXT_INSURER='103' then 'Reliance General Insurance Co. Ltd.'\r\n"
	 		+ "	   when TXT_INSURER='141' then 'Raheja QBE General Insurance Co. Ltd.'\r\n"
	 		+ "	    when TXT_INSURER='137' then 'Shriram General Insurance Co. Ltd.'\r\n"
	 		+ "		 when TXT_INSURER='134' then 'Universal Sompo General Insurance Co. Ltd.'\r\n"
	 		+ "		  when TXT_INSURER='90' then 'New India Assurance Co. Ltd.'\r\n"
	 		+ "		   when TXT_INSURER='58' then 'National Insurance Co. Ltd.'\r\n"
	 		+ "		    when TXT_INSURER='113' then 'Bajaj Allianz General Insurance Co. Ltd.'\r\n"
	 		+ "		    when TXT_INSURER='139' then 'Bharti AXA General Insurance Co. Ltd.'\r\n"
	 		+ "			 when TXT_INSURER='108' then 'Tata AIG General Insurance Co. Ltd.'\r\n"
	 		+ "			  when TXT_INSURER='149' then 'Magma HDI General Insurance Co. Ltd.'\r\n"
	 		+ "			   when TXT_INSURER='144' then 'SBI General'\r\n"
	 		+ "			    when TXT_INSURER='150' then 'Liberty General Insurance Company Ltd.'\r\n"
	 		+ "				 when TXT_INSURER='152' then 'Kotak Mahindra General Insurance'\r\n"
	 		+ "				  when TXT_INSURER='102' then 'Royal Sundaram Alliance Insurance Co. Ltd.'\r\n"
	 		+ "				   when TXT_INSURER='146' then 'HDFC General Insurance Co Ltd.'\r\n"
	 		+ "				    when TXT_INSURER='155' then 'Navi General Insurance Ltd'\r\n"
	 		+ "					 when TXT_INSURER='158' then 'GoDigit General Insurance Ltd.'\r\n"
	 		+ "					  when TXT_INSURER='159' then 'Edelweiss General Insurance Co. Ltd.'\r\n"
	 		+ "					   when TXT_INSURER='157' then 'Acko General Insurance Limited' \r\n"
	 		+ "					   else 'Insurer Not available' end TXT_INSURER,"
	 		+ "case when TYPE_OF_TRANSACTION ='I' and POLICY_END_DATE>= GETDATE() then 'Active'\r\n"
	 		+ "     when TYPE_OF_TRANSACTION ='I' and POLICY_END_DATE< GETDATE() then 'Expired'\r\n"
	 		+ "	 when TYPE_OF_TRANSACTION ='C' then 'Cancelled' end TYPE_OF_TRANSACTION,\r\n"
	 		+ "case when INSERTED_DATE between '01-apr-2020' and '31-mar-2021' then 'FY2021'\r\n"
	 		+ "     when INSERTED_DATE between '01-apr-2021' and '31-mar-2022' then 'FY2122'\r\n"
	 		+ "	 when INSERTED_DATE between '01-apr-2022' and '31-mar-2023' then 'FY2223' "
	 		+ "when INSERTED_DATE between '01-apr-2023' and '31-mar-2024' then 'FY2324' end INSERTED_DATE\r\n"
	 		+ " FROM iiw_mot_policy_history_uat WITH (NOLOCK)\r\n"
	 		+ "WHERE TXT_REG_NUMBER_VEHICLE in(:regno1,:regno2) order by TYPE_OF_TRANSACTION,INSERTED_DATE desc;",nativeQuery = true)
	 public List<VchvsEntity> basedOnBothRegnos(String regno1,String regno2);

}
